#SELECIONA O BANCO DE DADOS DO GOIT PARA USO
USE goit_db;

#REMOCAO DE ATIVIDADE AO AR LIVRE CRIADA NOS TESTES
DELETE FROM PARATV WHERE TABATV_Codigo = (
	SELECT TABATV_Codigo FROM TABATV WHERE TABATV_Titulo = "Caminhada no Jardim Botânico" AND TABATV_Data = "2023-10-24"
);
DELETE FROM TABATV WHERE TABATV_Titulo = "Caminhada no Jardim Botânico" AND TABATV_Data = "2023-10-24";

#REMOVE PRATICANTE INSERIDO NOS TESTES
DELETE FROM TABPRA WHERE TABUSU_Codigo = (
	SELECT TABUSU_Codigo FROM TABUSU WHERE TABUSU_Email = "antoniocarlos@gmail.com"
);
DELETE FROM TABUSU WHERE TABUSU_Email = "antoniocarlos@gmail.com";

#REMOVE PRATICANTE ADICIONAL INSERIDO NOS TESTES
DELETE FROM TABPRA WHERE TABUSU_Codigo = (
	SELECT TABUSU_Codigo FROM TABUSU WHERE TABUSU_Email = "wilsouza@gmail.com"
);
DELETE FROM TABUSU WHERE TABUSU_Email = "wilsouza@gmail.com";

#REMOVE INSTRUTOR INSERIDO NOS TESTES
DELETE FROM TABINS WHERE TABUSU_Codigo = (
	SELECT TABUSU_Codigo FROM TABUSU WHERE TABUSU_Email = "joaopedro@gmail.com"
);
DELETE FROM TABUSU WHERE TABUSU_Email = "joaopedro@gmail.com";

#REMOVE LOJISTA INSERIDO NOS TESTES
DELETE FROM TABLOJ WHERE TABUSU_Codigo = (
	SELECT TABUSU_Codigo FROM TABUSU WHERE TABUSU_Email = "empresabacana@gmail.com"
);
DELETE FROM TABUSU WHERE TABUSU_Email = "empresabacana@gmail.com";


